### ISSUE TITLE
Document k8s setup for compilation server

### ISSUE THREAD

**Issue by magland** [flatironinstitute/stan-playground#206]

**Comment by magland** [comment]
A couple notes

If you are running the compilation server so that the user inside the container is not root (for example, the default on kubernetes), then configure the following environment variables.

```
        env:
          - name: SWS_JOB_DIR
            value: /tmp/jobs
          - name: SWS_BUILT_MODEL_DIR
            value: /tmp/models
          - name: EM_CACHE
            value: /tmp/emcache
          - name: HOME
            value: /tmp
```

Also, for some reason the EM_CACHE env variable does not take effect if you call run.sh as the entrypoint. Instead you need to call uvicorn command directly.

Dylan said: "It's actually sort of bizarre, the EM_CACHE variable is somehow being lost in run.sh.  If I bypass run.sh and run uvicorn directly it seems to be kept."
